### ISSUE TITLE
Update gem on rubygems

### ISSUE THREAD

**Issue by pinzonjulian** [beanieboi/morrisjs-rails#14]
I'm upgrading my app to Rails 5.0.1 and found that morrisjs-rails was preventing bundle update to run.  Adding: `gem 'morrisjs-rails', github: 'beanieboi/morrisjs-rails` fixed it for me. However it would be nice to have it updated in rubygems.org.

Thanks!

**Comment by beanieboi** [comment]
whoops! thanks! just released `0.5.1.1` that works with Rails 5
