### ISSUE TITLE
ReferenceError: Can't find variable: jQuery

### ISSUE THREAD

**Issue by bjoernalbers** [beanieboi/morrisjs-rails#16]
Hello,

I had this error after following your install instructions:

> ReferenceError: Can't find variable: jQuery

The error could be solved by importing jquery.
I'm using Rails 5.1 which apparently doesn't come with jQuery by default.
Maybe you should update the install notes?

Cheers,
Björn

**Comment by beanieboi** [comment]
Thanks for opening this issues. i added a comment to the README, see 
https://github.com/beanieboi/morrisjs-rails/commit/6b8bb9332b4e8ccef2b48c98c701127f7ee3ddc1
